slick.dbs.default {
  driver = "slick.jdbc.PostgresProfile$"
  db {
    url = "jdbc:postgresql://localhost:5432/minesweeper"
    user = "minesweeper"
    password = "password"
    driver = "org.postgresql.Driver"
    connectionPool = "HikariCP"
    keepAliveConnection = true
    properties = {
      "reWriteBatchedInserts" = "true"
    }
  }
  "slick.db" {
    connectionPool = "HikariCP"
    keepAliveConnection = true
    numThreads = 10
  }
  db.sql = "debug"
}

akka {
  loglevel = "WARNING" # Global log level for Akka
  loggers = ["akka.event.slf4j.Slf4jLogger"] # Use SLF4J for Akka logging
  logging-filter = "akka.event.slf4j.Slf4jLoggingFilter"
}

# Suppress Apache Kafka logs
org.apache.kafka {
  loggers = [
    {
      name = "org.apache.kafka",
      level = "ERROR" # Reduce log verbosity for Kafka
    },
    {
      name = "org.apache.kafka.clients.consumer",
      level = "ERROR"
    },
    {
      name = "org.apache.kafka.clients.consumer.internals",
      level = "ERROR"
    }
  ]
}

# SLF4J specific overrides (optional)
logging.root.level = "INFO"
logging.level.org.apache.kafka = "ERROR"
logging.level.akka.kafka = "ERROR"
logging.level.akka.actor = "WARN"
